### ISSUE TITLE
M4 Investoigator - Time Left Calculation is wrong

### ISSUE THREAD

**Issue by AHM-amics** [Bruker-Amics/bugs_features#118] opened 2021-08-30 07:15 UTC
The Time left calculation is wrong. Especially if the system needs to change the kV and or uA values. The calculation should be from when the Xray collection starts and not from when the start button is pushed and the kV and uA values need to change or to open the m4 software. This often leads to an extremely long calculated measurement time, and therefore is only close to reality after a period time when this start delay is averaged out.

**Comment by jonathan-knapp** [comment] 2021-08-30 14:40
This is a duplicate of longstanding issue #9 in bugs_features. Closed due to duplication.

**Closed as completed** 2021-08-30 14:41 UTC
Labels: duplicate
