### ISSUE TITLE
Exported Ore Types Do Not Contain Groupings etc

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#344] opened 2023-02-03 02:29 UTC
When exporting the ore types, only the spectral references are saved, not the mineral groupings, spectrum tree steps or touch up steps. This means that ore types cannot be easily managed and / or archived into a single location without losing a great deal of embedded knowledge and functionality.

When exporting the ore types, it is a requirement to include all other associated information, groupings etc.

**Comment by jonathan-knapp** [comment] 2023-02-03 09:54
Yes, this is an issue. With the new file format we will better construct the ore type as a "method" - so this will be a high priority in 3.3.2.

**Comment by MarkGuo7** [comment] 2023-06-21 04:40
The grouping and steps information are in another file. So if want to export together, we need to figure out how to combine them. 
For the moment, the exporting is only mineral list.

**Comment by AlexeiDolgolyov** [comment] 2024-10-22 11:51
@ChiLyMan , Mark is right. Actual information about grouping/steps of oretypes is stored in a separate files (individual for each oretype) in folder `OretypeSetting` near `UserStd.db`. Seems like the best and easy thing we can do now is to also copy `OretypeSetting` folder (not only db file). Will it work as a fix of this issue?

**Comment by ChiLyMan** [comment] 2024-10-22 13:15
@AlexeiDolgolyov I guess for the current iteration of the software we don't have a choice to make the databases more transportable. But importantly when importing the database would the user need to manually import the grouping and steps as well, or can we somehow change the import to automatically import the steps and groups?

**Comment by AlexeiDolgolyov** [comment] 2024-10-22 13:19
@ChiLyMan , I've added export of ore type settings folder, so, I expect now, groups and steps should be imported automatically.

**Comment by ChiLyMan** [comment] 2024-10-22 20:40
@AlexeiDolgolyov 
I tried this by exporting using the Export Workflow option, and AMICS will write the DB file correctly.
<img width="226" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3BtQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7452f518cb82f210dcaa0878b0233ab529076a02/image.png" alt="image.png" />

<img width="614" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2xtQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1958500a2eedf36f04bcaa9b42a2b02fa254286e/image.png" alt="image.png" />

This DB has a test grouping associated with it. But then I Merge Workflow back into my common library:-
<img width="235" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdzFtQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dfbf1bc5aaf71e67545921ab1dce9edb5bb2c192/image.png" alt="image.png" />

The group is still missing.

Am I doing ti wrong?

**Comment by AlexeiDolgolyov** [comment] 2024-10-22 20:50
@ChiLyMan , probably I haven't got the real problem of the task. I thought the issue is associated with those actions:
<img width="156" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGxtQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bd1f3bf19f2df24e618baeb3c3afe64d648b663b/image.png" alt="image.png" />

**Comment by ChiLyMan** [comment] 2024-10-22 20:57
@AlexeiDolgolyov 
Sorry for not being clear the issue is really when trying to transport a single mineral list not the whole database. And like Mark said, if Groups and Steps are saved in another file then the only way to transport it is to also export the groups and steps as text file and have them imported at the same time.
In the past there was an option to export Groups and Spectrum tree as text file, but at somepoint this options for removed.

**Comment by AlexeiDolgolyov** [comment] 2024-10-23 08:25
@ChiLyMan , no problem. But then this task is really impossible to implement correctly without changing current DB structure.

**Comment by ChiLyMan** [comment] 2024-10-23 12:40
@AlexeiDolgolyov That's fine let's close this in anticipation of the new file format where we will get a chance to change the DB :) There is a workaround, as much as we hate workarounds, it is what it is with the current file format.

**Closed as completed by ChiLyMan** 2024-10-23 12:40 UTC
Labels: bug, enhancement, Atomic
