### ISSUE TITLE
Stage travel issue

### ISSUE THREAD

**Issue by MarkGuo7** [Bruker-Amics/bugs_features#54] opened 2021-06-04 05:11 UTC

**Comment by MarkGuo7** [comment] 2021-06-04 06:30
How much stage moving offset(tolerance) with rotation?
The stage travel issue may also cause the measure position is bit off with the setup area.
For this 28 samples holder, it may critical.

Driving to reference position:
![image.png](https://images.zenhubusercontent.com/60a59e61f0254ad3e154481a/f12a15e0-813f-4181-8f7d-7fd0daed6b4e)

![image.png](https://images.zenhubusercontent.com/60a59e61f0254ad3e154481a/ee4a3417-7ee0-4d85-a832-a6fb05cdee20)

Driving back to measurement:
Missing
![image.png](https://images.zenhubusercontent.com/60a59e61f0254ad3e154481a/b434c326-f927-4c32-91d2-0bf348086f13)

Overlap
![image.png](https://images.zenhubusercontent.com/60a59e61f0254ad3e154481a/175a4ac3-1955-4123-9cab-8c4a983e0b70)

**Comment by Matt-Power** [comment] 2021-06-04 07:19
For me, within a millimetre or so is acceptable - obviously the closer the better though. If I need to relocate accurately, I can use the quadrant type holder file (same as Gerda had). 

Would it be useful to have a known rotation calibration position or is the offset due to a relatively poor tolerance / backlash on the rotate?

**Comment by knapp-amics** [comment] 2021-06-16 17:21
Duplicate of Core #303, in progressw.

**Closed** 2021-06-16 17:21 UTC
Labels: P2: Required, duplicate
