### ISSUE TITLE
The measurement failed due to a mismatch between the image size in the measurement settings 

### ISSUE THREAD

**Issue by MarkGuo7** [Bruker-Amics/bugs_features#265] opened 2022-08-02 00:13 UTC
Hi Mark,

Thank you for the license key for our processing PC yesterday.

We have been running AMICS a lot recently and we expect to keep up this high pace for the near future. There are two items that I wish to bring to your attention please:

1.	On our last AMICS run the measurement failed due to a mismatch between the image size in the measurement settings and that from the microscope. The strange part is that this happened mid-run. 
See log files attached. Do you have an idea as to what happened here?

2.	There is a bug in the version of 3.3 that we have. In Process, the previous ore types are not directly compatible. When viewing the mineral standards, the reference spectra seem to have some incorrect scaling and the corresponding element lines are not correct. However, the same standard in version 3.2 displays correctly. Could you also look into this please? Screenshots attached.

Please let me know if the 7-Zip files don’t work.

Kind regards,
Scarlett

[Uploading... 01_ImageSize.7z][Uploading... 02_SpectralShift.7z]

**Comment by ChiLyMan** [comment] 2022-09-02 20:39
@MarkGuo7 Has this been resolved and been tested?

**Comment by MarkGuo7** [comment] 2022-09-13 00:00
@ChiLyMan We couldn't repeat this issue and no further update from Scarlett after.
Not sure what happened, but I guess we can close it for now.

**Comment by ChiLyMan** [comment] 2022-09-13 00:08
@MarkGuo7 Let me check with her before we close this out.

**Comment by ChiLyMan** [comment] 2022-09-14 17:49
Issue #1 Could not be repeated and client has not seen the issue reappear since the one time this occurred. Closing issue for now.
Issue #2 Client has confirmed this was fixed and is working properly.

**Comment by ChiLyMan** [comment] 2022-09-26 14:26
Issue has occurred again at client's site. Review of the the logs shows the system acquiring the BSE image at a different resolution than expected. Access to the measurement file has been requested to help resolve this issue.

**Comment by ChiLyMan** [comment] 2022-10-25 18:16
NOTE: Waiting for signed NDA with Rio to "see" the measurement which is causing the issue because this only seems to be occurring on certain measurements. And looking at the log Espirt/AMICS seems to be changing the image resolution the BSE is acquired mid run. We will need to see the measurement settings and results to see if there is a setting bug/conflict causing this change in BSE resolution acquisition.
Elanor is in contact with Chad regarding the required NDA.

**Closed as completed** 2023-02-09 03:56 UTC
Labels: bug, P1: Mission Critical
