### ISSUE TITLE
BUG - MAJOR - AMICS PROCESS - BATCH - Occasional missing fields in BSE during batch extract

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#385] opened 2023-06-09 19:12 UTC
When running a batch export of the BSE images, I often get a couple of images where there are missing fields. It is completely random which samples / which fields will be missing. Some batches will be fine, others will have 1 or 2 images with missing fields.

Doesn't seem to happen to Mineral images.

**Comment by ChiLyMan** [comment] 2023-06-09 19:26
Further discussion about this bug, the missing fields only occur during batch processing, and returning to the same sample to do a manual export result in proper export of the BSE.
So the issue is linked to the batch exporting of large # of BSE images, are we running into memory issues or HDD access timeout issues?

**Comment by Matt-Power** [comment] 2023-06-09 19:33
Just to add, it can be during small batches too (e.g. happened with a batch of 14 last night). Also, in case it helps track down, we almost always use a field size of 800x600.

**Comment by jonathan-knapp** [comment] 2023-07-20 00:24
@Matt-Power, we are having issues reproducing this. When you encounter it, will you please let us know? We are going to add logging so we can catch it. This logging will be in the next beta release.

**Closed as completed** 2023-07-20 00:24 UTC
Labels: bug
