### ISSUE TITLE
M4 Investigator - GUI Labels

### ISSUE THREAD

**Issue by AHM-amics** [Bruker-Amics/bugs_features#113] opened 2021-08-30 07:06 UTC
The “WD” concept is not correct M4 and should be labelled differently, i.e. Z stage height. 

This is a generic issue throughout the software where everything is expressed from a SEM point of view. Many labels/buttons/information is thus incorrectly expressed when using the software on a M4 (or microXRF system)

**Comment by jonathan-knapp** [comment] 2021-08-30 14:44
This is a duplicate of Core #394 that is in the testing workflow.

**Closed as completed by jonathan-knapp** 2021-08-30 14:44 UTC
Labels: duplicate
