### ISSUE TITLE
BSE Batch Export Fails

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#216] opened 2022-04-05 05:30 UTC
Think this has been fixed several times but then creeps back in somehow: more often than not, the batch BSE image export fails. It seems to be a bit random - sometimes it works but mostly just sits at the first sample apparently doing nothing for several minutes (10+) until either crashing or I lose interest and kill the batch. It also sometimes cycles through all of the samples and gives an "Export failed" message.
When it does work, the images export in ~10 seconds i.e. it's not the samples that are the issue.

**Comment by jonathan-knapp** [comment] 2022-07-08 14:10
duplicate of #189. Comment added to 189.

**Closed as completed** 2022-07-08 14:10 UTC
Labels: duplicate
