### ISSUE TITLE
M4 Investigator - Start Button (x2)

### ISSUE THREAD

**Issue by AHM-amics** [Bruker-Amics/bugs_features#110] opened 2021-08-30 07:02 UTC
There are two start buttons. The start button on the main toolbar is often greyed out. This is especially so if I do a measurement and then add a new measurement the start button is greyed out and I need to use the button on the right.

**Comment by jonathan-knapp** [comment] 2021-08-30 14:47
THis is a duplicate of Core#389 listed as done and ready for testing in the next build. Will be closed.

**Closed as completed by jonathan-knapp** 2021-08-30 14:47 UTC
Labels: duplicate
