### ISSUE TITLE
Batch extraction of Association Data Doesn't Work

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#194] opened 2021-12-17 23:21 UTC
If I run a batch calculation for mineral associations, the process completes but no spreadsheet is generated at the end.

**Comment by Matt-Power** [comment] 2022-07-09 20:11
This still does not work in v. 3.3.0.1158. It works through all of the samples and then creates a junk xml file that excel cannot open (and it's 1k in size so suspect empty anyway).

**Comment by van-amics** [comment] 2022-07-27 22:49
Hi Matt. Since I cannot reproduce the issue with my small samples, can you please send me the very batch that caused this problem, so I can reproduce it and hopefully get to the bottom of this one. Thanks.

**Comment by Matt-Power** [comment] 2022-07-27 23:02
I'm honestly very surprised you cannot recreate - it happens on literally every dataset I have ever tried it on (lots of them). It is also independent of ore type and computer. Just choose any of the projects I've previously sent over - it will happen with those. 

Go to calculation table, select associations and run any batch. It will go through the motions but nothing happens at the end.

**Comment by jonathan-knapp** [comment] 2022-08-24 13:13
Matt, was this issue resolved?

**Comment by Matt-Power** [comment] 2022-08-24 16:11
No

**Comment by ChiLyMan** [comment] 2022-09-02 21:06
@Matt-Power Hey Matt. I just tested this on my system here. Attached is the XML and the XLS file generate. Ignore the crappy result these are random test sample, included those two dataset you've sent me. Is this the output you are expecting?
[https://app.zenhub.com/files/368966218/7f86afaa-0d3e-4ec0-b4b7-1a6ad44e3d2b/download](https://app.zenhub.com/files/368966218/7f86afaa-0d3e-4ec0-b4b7-1a6ad44e3d2b/download)

[Uploading... Test_Batching.xml]

**Comment by Matt-Power** [comment] 2022-09-02 21:10
@ChiLyMan Sorry, can't access that - can you email direct to me please?

**Comment by Matt-Power** [comment] 2022-09-02 21:27
Thanks and yes, that works. Is that fix in the latest build?

**Comment by ChiLyMan** [comment] 2022-09-02 21:31
Yes, I did this on build 3.3.0.1245.
Closing the issue now.

**Closed as completed by ChiLyMan** 2022-09-02 21:31 UTC
Labels: bug
