### ISSUE TITLE
Crash on Sync Ore Type Entries

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#106] opened 2021-08-26 20:48 UTC
If I compare result file with an ore type, show difference and then sync the differences, Process crashes out.

**Comment by jonathan-knapp** [comment] 2021-08-30 15:01
This is a duplicate of Core #341 that is listed as "in progress" and will be closed. This will be fixed before 3.2 release and included in the next Beta

**Closed as completed** 2021-08-30 15:01 UTC
Labels: duplicate
