### ISSUE TITLE
Problem with user standard oretype list after installing vs 3.3 and with importing a database

### ISSUE THREAD

**Issue by GGloy** [Bruker-Amics/bugs_features#264] opened 2022-07-28 02:11 UTC
I have noticed this issue on my laptop and now also at UQ online system.

After installing vs3.3 on the UQ system, when returning to vs3.2 - most of the user std oretypes where gone! Fortunately could restore from the user std backup - but then it was noted that some oretypes have no minerals listed. 

Again, I could restore these minerals by manually merging the oretype again from the database backup one-by-one.

So in vs3.3 after installing if I click on "classification" (by the way this term is still  not clear to what this is pointing to) then I will get this window. 
![image.png](https://images.zenhubusercontent.com/60af4a22d2c5ea1082755c53/7c2c1d3c-ea43-4c19-beb7-50f0b216ef16)

Even after waiting a couple of minutes nothing happens, but if I click cancel it seems fine - I can see the oretypes.

When importing a different database however i get this message (in both 3.3 and vs3.2)
![image.png](https://images.zenhubusercontent.com/60af4a22d2c5ea1082755c53/9011b93c-35c7-4f04-ab9b-06f512df0865)

This is critical to fix.

**Comment by robbmcleod** [comment] 2022-09-24 00:30
So should `OreTypes.db` be located in `C:\ProgramData\AMICS-common` then?

**Comment by MarkGuo7** [comment] 2022-09-25 23:42
The question is the new installation will be compatible with previous installation or not.
I guess we shouldn't change these old versions. And if the different version AMICS use different setting files, basically they are different product.

So maybe we should consider the 3.3 as a different AMICS, and it will support multi-version installation afterward.

We also need to discuss which file need to be shared between different versions and which ones not.

**Comment by jonathan-knapp** [comment] 2022-11-16 13:38
Would a solution be that 3.3 will not interfere with a 3.2 install but not share any files or settings? This is acceptable to me.

**Comment by MarkGuo7** [comment] 2022-11-27 23:16
If 3.2 and 3.3 use different settings, different user standard files, they are two products basically. 
If users changed one product, added a standard to database, the other one didn't reflect the changes.
So they need to copy over all the changes every time. I am not sure that it is the side by side means.

**Comment by ChiLyMan** [comment] 2023-02-14 16:18
Guys,
Part of the problem also seems to be access right to the folder. Ran into this issue in PetroBras when users do not have read/write access to the AMICS folder. Once we got IT to give the users read/write access the issue is resolved.
As for having 3.2 and 3.3 side by side, right now suggest we leave it 3.3 sharing the files in the AMICS folder in ProgramData, until we do a final release of 3.3 as some clients are still needing to jump from 3.3 to 3.2 due to some functions works only on 3.2 right now (not many functions just a couple).

**Comment by ChiLyMan** [comment] 2023-10-27 23:38
ALL, I'm closing this because this is a known problem with using the ProgramData folder to store these files and short of moving the location of these files, I will just add this to "known issues" as part of the installation instruction/troubleshooting.

**Closed as completed by ChiLyMan** 2023-10-27 23:38 UTC
Labels: bug, P2: Required
