### ISSUE TITLE
BUG - MAJOR - AMICS 3.3.0.1812 - PROCESS - #FFFFFF treated as transparent in live view, opaque white in export

### ISSUE THREAD

**Issue by jkabel** [Bruker-Amics/bugs_features#382] opened 2023-06-02 17:50 UTC
Live view: ![image](https://github.com/Bruker-Amics/bugs_features/assets/12158231/73442ff7-1965-40fe-8a80-3e15f3d29157)
Export view: 
![image](https://github.com/Bruker-Amics/bugs_features/assets/12158231/6d2c69c2-b2f5-410d-8d43-1c10ab71c4c5)

Attempting to work around issue #364, I created a grouping with zircon (pink), apatite (blue), and other (everything else, white, FFFFFF) and exported it. This occurs with both "Export Image" and "Export Screen".

FFFFFF appears to be treated as transparent in the live view and opaque in the exported image. Expected behaviour is that the exported image would reflect the live view (WYSIWYG style).

**Comment by jonathan-knapp** [comment] 2023-06-14 00:57
Still happening in 3.3.0.1812. Related to the image export bug. Makes image exports unusable, so marked as major.

**Comment by ChiLyMan** [comment] 2023-07-05 18:12
Just tested this on build 1854 and looks fixed.
Original color scheme:
![image.png](https://images.zenhubusercontent.com/62f264fb4831bda01fb7d454/bb57584b-76aa-4489-874a-574195c9570e)
Screen view (quartz is FFFFFF)
![image.png](https://images.zenhubusercontent.com/62f264fb4831bda01fb7d454/36ec9134-ebb1-47ca-8947-c5f65148f6f8)
Export with Qzt = FFFFFF
![37ZK16H11-Matrix Mapping_Mineral__Image.png](https://images.zenhubusercontent.com/62f264fb4831bda01fb7d454/2a75de51-40c4-4817-80af-9009c14d8b45)

**Closed as completed by ChiLyMan** 2023-07-05 18:12 UTC
Labels: bug

**Comment by jkabel** [comment] 2023-07-05 18:14
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  Did you try it with the BSE underlay on?-Jacob                                                                                                                                                                                                                                                                                                                        From: ***@***.***: July 5, 2023 11:13 a.m.To: ***@***.***: ***@***.***: ***@***.***; ***@***.***: Re: [Bruker-Amics/bugs_features] BUG - MAJOR - AMICS 3.3.0.1812 - PROCESS - #FFFFFF treated as transparent in live view, opaque white in export (Issue #382)  
Closed #382 as completed.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by ChiLyMan** [comment] 2023-07-05 18:17
With BSE Underlay on :)
![image.png](https://images.zenhubusercontent.com/62f264fb4831bda01fb7d454/deea8964-4dfd-4c77-9b26-92b71c1348b4)

**Comment by jkabel** [comment] 2023-07-05 18:19
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  Perfect!                                                                                                                                                                                                                                                                                                                         From: ***@***.***: July 5, 2023 11:17 a.m.To: ***@***.***: ***@***.***: ***@***.***; ***@***.***: Re: [Bruker-Amics/bugs_features] BUG - MAJOR - AMICS 3.3.0.1812 - PROCESS - #FFFFFF treated as transparent in live view, opaque white in export (Issue #382)  
With BSE Underlay on :)


—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by jkabel** [comment] 2023-09-12 23:53
Hi everyone, this has made its way back into 1903.

Live image from AMICS:
![image](https://github.com/Bruker-Amics/bugs_features/assets/12158231/061d14fb-14e9-49f3-97da-9b7572561f8f)

Exported image, all minerals, BSE underlay on:
![image](https://github.com/Bruker-Amics/bugs_features/assets/12158231/afde973a-be95-4fa2-b119-2d19cd8d6911)

**Comment by ChiLyMan** [comment] 2023-09-14 14:57
Morning Jacob,

I’m going to update the Git report but wanted to send you this first.

The issue you are seeing is not a bug, it is the way the measurement was made and the grouping that was used.
The current set up of the measurement using the Sulfides Only grouping is generating this output because of two reasons:-
1)	Those large white squares were classified as Pores, and Pores are colored as #FFFFFF which is white. And so AMICS is exporting the BSE underlay with mineral data and the “Pores” are being exported as well, resulting in white squares. I think it is generating square pores because of the segmentation setting causing it to segment a field into pores, with some non-pores sprinklered in.
2)	The disseminated white is caused by the large percentage of the sample being “Unknown” using the “Sulfides Only” group, and since Unknown are set to #FFFFFF, they are also getting exported during the image export as White pixels, which is exactly what we are telling AMICS to do.
![TEST](https://github.com/Bruker-Amics/bugs_features/assets/84643841/c66986e4-850a-4c14-89e5-facc175175a0)
Some long-term solutions:-
•	Adjust the measurement parameters for the BSE threshold to not generate Pores, so maybe a more defined BSE calibration.
•	I notice on the BSE image there seems to be a central section which is “different” from the edge, not sure if this is a sample but if not the same then maybe SEM set up, which help mitigate the generation of “Pores”
•	Updating the library to reduce the percentages of unknown, or change the analysis setting to avoid these unknown?

Some quick fixes with the data in-hand:-
•	Go to “Cleanup” and run the “BG and Pore” removal step.
•	Also run the “Cleanup” step to remove “Unxrayed” segments as well.
•	Change the color of the “Others” to grey.
You can then generate the below image, you notice all the “Pores” are gone now, but you still see the grey colored “Others”
 ![Removed_Pores](https://github.com/Bruker-Amics/bugs_features/assets/84643841/b859ebb9-bda6-42d1-adef-e54e9e14972b)
Or nuclear option:-
•	If you want to go full ICBM mode, go to grain panel while in “Sulfides Only” group, and filter out all the “Others” of any size, and convert them to “Background”
You will then get a clean image like below, BUT NOTE This will screw up you data for the other groupings because the student had minerals also grouped into “Others”
![Grain_Panel](https://github.com/Bruker-Amics/bugs_features/assets/84643841/ee4da6c4-2a07-4e83-ac9c-c0159d580b00)

**Comment by jkabel** [comment] 2023-09-14 18:48
Hi Chi,

You can't really have this one both ways. There is a bug here. Either the bug is that #FFFFFF is treated as transparent in the live view, or the bug is that #FFFFFF is treated as opaque in the exported view.

Personally, I think that treating #FFFFFF as transparent in both view offers substantial utility. Batch processing can use that route to produce maps that don't show unknown or pore space. Your method of producing an analog takes substantial time and manual data manipulation. There should be ways in AMICS to export maps that only show phases of interest quickly and in an automation friendly fashion. Some people (as in this case) simply don't care about the things that aren't the phases they're interested in, and want them to "go away" in as quick and convenient a way as possible.

**Comment by ChiLyMan** [comment] 2023-09-14 19:21
Hi Jacob,
If all you are looking to do is highlight the Sulphides and not show the Others, depending on the version you are running right now, just select all the target phases of interest and leave Other unselected.
![image](https://github.com/Bruker-Amics/bugs_features/assets/84643841/ba2eed63-cfbd-4051-a983-dcaf4f610aa6)
This is then your live view in AMICS:-
![image](https://github.com/Bruker-Amics/bugs_features/assets/84643841/5f8003fe-078d-4a78-b6da-4e5c00746f33)
And if you now export the image:-
![image](https://github.com/Bruker-Amics/bugs_features/assets/84643841/f4519ffc-b67a-49bf-b063-539b499e3489)
Does this meet your needs? Of course, you can select which colors you want active on the export. This does not permanently remove the pore or "correct" the data in anyway.

The only thing this does not achieve is the ability to do this via batch export mode. If you give me a little time, I think I can probably come up with series of spectrum tree or touch up steps which would allow for batch export of images to export only certain minerals. But if we had a way to select certain minerals to export as an option in the batch exporter would be a good idea.

**Comment by jkabel** [comment] 2023-09-14 23:12
Hi Chi,

It looks like this behaviour is also broken on 1903.

Here's the selections:
![image](https://github.com/Bruker-Amics/bugs_features/assets/12158231/f21e2ed9-6979-471c-affe-a0ae4118cd2e)

The live image:
![image](https://github.com/Bruker-Amics/bugs_features/assets/12158231/7982e5b1-3a1e-44ca-bd3b-5973941bb5fe)

And the exported image:
![image](https://github.com/Bruker-Amics/bugs_features/assets/12158231/0a534481-68a6-484f-9bf0-3565fea097f2)

Also the selection appears to be a little broken, selecting only the last item turned on/off in an unpredictable manner:
![image](https://github.com/Bruker-Amics/bugs_features/assets/12158231/c340d960-fd9c-4d32-9367-b305fb24f89a)
